FROM node:20-bullseye-slim

WORKDIR /app
COPY package.json .

RUN apt update && \
    apt install --yes libcurl4 --no-install-recommends && \
    npm install && \
    npx playwright install chromium-headless-shell --with-deps && \
    node -e "require('mongodb-memory-server').MongoMemoryServer.create().then(s => s.stop())" && \
    rm -rf /var/lib/apt/lists/*

COPY . .

ENV NODE_ENV=development

EXPOSE 3000

CMD ["npm", "run", "dev"]
