FROM node:20-slim

WORKDIR /app
COPY package.json .

RUN npm install && \
    npx playwright install chromium-headless-shell --with-deps

COPY . .

ENV NODE_ENV=development

EXPOSE 3000

CMD ["npm", "run", "dev"]
