export const PERMISSIONS = {
    URL_VIEW: 'URL.VIEW',
    URL_DELETE: 'URL.DELETE',
    URL_PROCESS: 'URL.PROCESS',
    SCRAPPING_STATUS_VIEW: 'SCRAPPING.STATUS.VIEW',
    SCRAPPING_STATUS_MODIFY: 'SCRAPPING.STATUS.MODIFY'
};

export const ROLES = {
    ADMIN: 'admin',
    STAFF: 'staff'
};
